# Generated by Django 5.2 on 2025-04-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageocr',
            name='structured_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
